### ISSUE TITLE
Scala.js settings

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/sbt-gsp#3]
I wonder if we should include scala.js settings here. We are not going to use them everywhere but in many modules we will

Given we explicitly say what projects cross compile it shouldn't affect pure jvm modules

**Comment by swalker2m** [comment]
Yes, I think we can define settings such that they are available to apply in any project even if they aren’t needed in every project. I plan to do the same with the publishing settings.

**Comment by cquiroz** [comment]
publishing settings make sense. I still want to limit all the extra plugins in sbt. it is easy to get carried on

**Comment by swalker2m** [comment]
The common settings are [available now from the plugin](https://github.com/gemini-hlsw/sbt-gsp/pull/8).  I'll call this done for now, but we might want to include the scala-js plugins at some point assuming that it is mostly harmless for projects that don't use it and that having the same version of these across all builds is reasonable.
